<?php
$demoList = array(
    0  => array(
        'id'           => 'google-php-lib-simple',
        'title'        => 'Google PHP Library Simplified',
        'url'          => '//subinsb.com/login-with-google-oauth-without-using-google-php-library',
        'd'            => '//demos.sim/google-php-lib-simple',
        'downloadFile' => 'google-php-lib-simple',
        //'down'  => 's/x8mcoaqs3yrwumxm5bpb',urlc
    ),
    1  => array(
        'id'           => 'secure-php-login-system',
        'title'        => 'MySQL injection free Secure Login System - PHP',
        'url'          => '//subinsb.com/create-mysql-injection-free-secure-login-system-in-php',
        'd'            => '//demos.sim/secure-php-login-system',
        'down'         => 's/jb5620r05dn0tefucyej',
        'downloadFile' => 'secure-php-login-system',
    ),
    2  => array(
        'id'           => 'htpasswd-password-generator',
        'title'        => 'Password for HTPASSWD Generator',
        'url'          => '//subinsb.com/password-protect-folder-using-htaccess',
        'd'            => '//demos.sim/htpasswd-password-generator',
        'down'         => 's/j793rse5ge362mq2g57c',
        'downloadFile' => 'htpasswd-password-generator',
    ),
    3  => array(
        'id'           => 'ajax-image-upload-jquery',
        'title'        => 'Uploading An Image Using AJAX In jQuery With PHP',
        'url'          => '//subinsb.com/uploading-an-image-using-ajax-in-jquery-with-php',
        'd'            => '//demos.sim/ajax-image-upload-jquery',
        'down'         => 's/bld3mcpso1ak8d9d6j9g',
        'downloadFile' => 'ajax-image-upload-jquery',
    ),
    4  => array(
        'id'           => 'url-shortener',
        'title'        => 'URL Shortener',
        'url'          => '//subinsb.com/create-your-own-url-shortening-service-using-php-jquery',
        'd'            => '//demos.sim/url-shortener',
        'down'         => 's/ixbvk2b45r4al6lqylbt',
        'downloadFile' => 'url-shortener',
    ),
    5  => array(
        'id'           => 'text-editor-jquery',
        'title'        => 'Simple Text Editor Created Using jQuery',
        'url'          => '//subinsb.com/create-text-editor-using-html-jquery-like-in-blogger',
        'd'            => '//demos.sim/text-editor-jquery',
        'down'         => 's/jnkbr9q290yjvhuzq93z',
        'downloadFile' => 'text-editor-jquery',
    ),
    6  => array(
        'id'           => 'change-url-without-reloading',
        'title'        => 'Change URL Without Reloading Page',
        'url'          => '//subinsb.com/how-to-change-the-browser-url-without-refreshing-page-html5',
        'd'            => '//demos.sim/change-url-without-reloading',
        'down'         => 's/iub0c1u74c3drbgd0ckf',
        'downloadFile' => 'change-url-without-reloading',
    ),
    7  => array(
        'id'           => 'html-css-js-editor',
        'title'        => 'How To Create A HTML Code Editor Using jQuery and HTML',
        'url'          => '//subinsb.com/how-to-create-a-html-css-js-code-editor-using-jquery',
        'd'            => '//demos.sim/html-css-js-editor',
        'down'         => 's/botl3vh4mxohekprisfo',
        'downloadFile' => 'html-css-js-editor',
    ),
    8  => array(
        'id'           => 'jquery-username-availability-check',
        'title'        => 'Simple jQuery Username Availablity Checker',
        'url'          => '//subinsb.com/how-to-create-a-simple-username-availability-checker-using-jquery-and-php',
        'd'            => '//demos.sim/jquery-username-availability-check',
        'down'         => 's/xesjodgbr03l3ja7j3kc',
        'downloadFile' => 'jquery-username-availability-check',
    ),
    9  => array(
        'id'           => 'jquery-password-strength-checker',
        'title'        => 'Simple jQuery Password Strength Checker',
        'url'          => '//subinsb.com/how-to-create-a-simple-password-strength-checker-using-jquery',
        'd'            => '//demos.sim/jquery-password-strength-checker',
        'down'         => 's/zwvyrapzdneis4dli6jr',
        'downloadFile' => 'jquery-password-strength-checker',
    ),
    10 => array(
        'id'           => 'jquery-birthday-form',
        'title'        => 'jQuery Birthday Form Field & Checker',
        'url'          => '//subinsb.com/how-to-add-a-simple-birthday-field-in-a-form-using-jquery',
        'd'            => '//demos.sim/birthday-form-jquery',
        'down'         => 's/mu8efhble12vf1bjiuut',
        'downloadFile' => 'jquery-birthday-form',
    ),
    11 => array(
        'id'           => 'check-internet-connection-js-jquery',
        'title'        => 'Check If Internet Connection Exists In jQuery & Javascript',
        'url'          => '//subinsb.com/how-to-check-if-internet-connection-exists-in-jquery-javascript',
        'd'            => '//demos.sim/check-internet-connection-js-jquery',
        'down'         => 's/1aopikyfm17h18zgvolm',
        'downloadFile' => 'check-internet-connection-js-jquery',
    ),
    12 => array(
        'id'           => 'php-web-crawler',
        'title'        => 'Web Crawler in PHP',
        'url'          => '//subinsb.com/how-to-create-a-simple-web-crawler-in-php',
        'd'            => '//demos.sim/php-web-crawler',
        'down'         => 's/26vvx8ogxw8dgslp5oqx',
        'downloadFile' => 'php-web-crawler',
    ),
    13 => array(
        'id'           => 'imgur-api-image-upload',
        'title'        => 'Upload Images Using ImgUr API',
        'url'          => '//subinsb.com/uploading-images-using-imgur-api-in-php',
        'd'            => '//demos.sim/imgur-api-image-upload',
        'down'         => 's/ziw858fxuwelc5onpokg',
        'downloadFile' => 'imgur-api-image-upload',
    ),
    14 => array(
        'id'           => 'contact-form-mailgun',
        'title'        => 'Contact Form That Sends Messages Via E-Mail',
        'url'          => '//subinsb.com/mail-contact-form-in-php-with-mailgun',
        'd'            => '//demos.sim/contact-form-mailgun',
        'down'         => 'f8s8ccabcuey/s/pgc27ui6zctumkmulfia',
        'downloadFile' => 'contact-form-mailgun',
    ),
    15 => array(
        'id'           => 'jquery-smention',
        'title'        => 'jQuery sMention Plugin - Implement @mention on Inputs',
        'url'          => '//subinsb.com/integrate-mentions-to-fields-jquery-smention-plugin',
        'd'            => '//demos.sim/jquery/smention',
        'down'         => 'gjys13rzolod/s/4bap9bxwi5d2d8e5au5z',
        'downloadFile' => 'jquery-smention',
    ),
    16 => array(
        'id'           => 'php-group-chat',
        'title'        => 'How To Create Group Chat In PHP With MySQL, jQuery & AJAX',
        'url'          => '//subinsb.com/group-chat-in-php-with-ajax-jquery-mysql',
        'd'            => '//demos.sim/php/chat',
        'down'         => 'b4i8alv3xd7k/s/6wle8d7632fcj0w2j80x',
        'downloadFile' => 'php-group-chat',
    ),
    17 => array(
        'id'           => 'php-text-to-speech',
        'title'        => 'Making Text To Speech In PHP With Google Translate',
        'url'          => '//subinsb.com/text-to-speech-in-php-with-google-translate',
        'd'            => '//demos.sim/php/speech',
        'down'         => '404x12bqlmmu/s/y15htxpnn21icg2f9hxz',
        'downloadFile' => 'php-text-to-speech',
    ),
    18 => array(
        'id'           => 'send-mails-via-smtp-server-gmail-outlook',
        'title'        => 'Send E-Mails Via SMTP Server In PHP - GMail & Outlook',
        'url'          => '//subinsb.com/send-mails-via-smtp-server-gmail-outlook-php',
        'd'            => '//open.subinsb.com/invite',
        'down'         => 'n7t4ppks7xyn/s/f77onz2xf8ruzonhqc9y',
        'downloadFile' => 'smtp-mail-send',
    ),
    19 => array(
        'id'           => 'php-check-if-string-is-html',
        'title'        => 'Check If A String Is HTML In PHP',
        'url'          => '//subinsb.com/php-check-if-string-is-html',
        'd'            => '//demos.sim/php/isHTML',
        'down'         => '',
        'downloadFile' => '',
    ),
    20 => array(
        'id'           => 'php-check-if-string-is-json',
        'title'        => 'Check If String Is JSON In PHP',
        'url'          => '//subinsb.com/php-check-if-string-is-json',
        'd'            => '//demos.sim/php/isJSON',
        'down'         => '',
        'downloadFile' => '',
    ),
    21 => array(
        'id'           => 'php-username-email-login',
        'title'        => 'Log In With Username / E-Mail',
        'url'          => '//subinsb.com/php-log-in-with-username-email',
        'd'            => '//demos.sim/php/username-email-login',
        'down'         => '',
        'downloadFile' => '',
    ),
    22 => array(
        'id'           => 'php-download-zip-file',
        'title'        => 'Download Zip Files Dynamically in PHP',
        'url'          => '//subinsb.com/php-download-zip-file',
        'd'            => '//demos.sim/php/download-zip',
        'down'         => '',
        'downloadFile' => '',
    ),
    23 => array(
        'id'           => 'php-chat-typing-status',
        'title'        => "Group Chat In PHP With Users' Typing Status",
        'url'          => '//subinsb.com/php-group-chat-with-user-type-status',
        'd'            => '//demos.sim/php/chat-typing-status',
        'down'         => '6276vjhzyuni/s/di7yi98bnqo34mzn7n8x',
        'downloadFile' => 'php-chat-typing-status',
    ),
    24 => array(
        'id'       => 'php-search-engine',
        'title'    => 'Search Engine In PHP, MySQL With Crawler',
        'url'      => '//subinsb.com/search-engine-in-php-part-1',
        'd'        => '//search.subinsb.com',
        'down'     => '//github.com/subins2000/search/archive/master.zip',
        'download' => array(
            'service' => 'github',
            'url'     => '//github.com/subins2000/search/archive/master.zip',
        ),
    ),
    25 => array(
        'id'           => 'php-identify-remote-os',
        'title'        => 'Identify Remote OS By IP Address',
        'url'          => '//subinsb.com/php-identify-remote-os',
        'd'            => '//demos.sim/php/identify-remote-os',
        'down'         => '',
        'downloadFile' => '',
    ),
    26 => array(
        'id'           => 'php-advanced-crawler',
        'title'        => 'Advanced Crawler In PHP',
        'url'          => '//subinsb.com/php-create-advanced-web-crawler',
        'd'            => '//demos.sim/php/advanced-crawler',
        'down'         => 'r11x87prdpc9/s/sf7reidj6l4i1d5twuql',
        'downloadFile' => 'php-advanced-crawler',
    ),
    27 => array(
        'id'       => 'php-logsys',
        'title'    => 'PHP Login System',
        'url'      => '//subinsb.com/php-logsys',
        'd'        => '//demos.sim/php/loginSystem',
        'down'     => '//github.com/subins2000/logSys/archive/master.zip',
        'download' => array(
            'service' => 'github',
            'url'     => '//github.com/subins2000/logSys/archive/master.zip',
        ),
    ),
    28 => array(
        'id'           => 'php-minify-js-code',
        'title'        => 'Minify JavaScript Using PHP',
        'url'          => '//subinsb.com/php-minify-js-code',
        'd'            => '//demos.sim/php/jsMin',
        'down'         => 'b5wg3mjz3ba1/s/1xmre7m5wwys7lms6651',
        'downloadFile' => 'php-minify-js-code',
    ),
    29 => array(
        'id'           => 'jquery-animated-ajax-login-form',
        'title'        => 'Animated AJAX Login Form With jQuery',
        'url'          => '//subinsb.com/jquery-animated-ajax-login-form',
        'd'            => '//demos.sim/jquery/ajaxLogin',
        'down'         => 's/qlv8a8lje4ktjpjfkke3',
        'downloadFile' => 'jquery-animated-ajax-login-form',
    ),
    30 => array(
        'id'           => 'php-websocket-chat',
        'title'        => 'Live Group Chat With PHP, jQuery & WebSocket',
        'url'          => '//subinsb.com/live-group-chat-with-php-jquery-websocket',
        'd'            => '//demos.sim/php/websocketChat',
        'down'         => 's/qkuz7ln0zloqslfvzs67',
        'downloadFile' => 'php-websocket-chat',
    ),
    31 => array(
        'id'       => 'html5-record-mic-voice',
        'title'    => 'Record, Play, Download Microphone Voice With HTML5',
        'url'      => '//subinsb.com/html5-record-mic-voice',
        'd'        => '//demos.sim/Francium/voice',
        'down'     => '//github.com/subins2000/francium-voice/archive/master.zip',
        'download' => array(
            'service' => 'github',
            'url'     => '//github.com/subins2000/francium-voice/archive/master.zip',
        ),
    ),
    32 => array(
        'id'           => 'jquery-chess',
        'title'        => 'Create Chess Game With jQuery',
        'url'          => '//subinsb.com/jquery-chess-game',
        'd'            => '//demos.sim/jquery/chess',
        'down'         => 's/6295t23lh4vj2qk6dz0h',
        'downloadFile' => 'jquery-chess',
    ),
    33 => array(
        'id'           => 'newton-color-disc',
        'title'        => 'Newton Color Disc With jQuery',
        'url'          => '//subinsb.com/newton-color-disc',
        'd'            => '//demos.sim/jquery/color-disc',
        'downloadFile' => 'newton-color-disc',
    ),

    34 => array(
        'id'       => 'francium-translator',
        'title'    => 'Free Google Translator API',
        'url'      => '//subinsb.com/francium-translator',
        'd'        => '//demos.sim/Francium/Translator',
        'down'     => '//github.com/subins2000/francium-translator/archive/master.zip',
        'download' => array(
            'service' => 'github',
            'url'     => '//github.com/subins2000/francium-translator/archive/master.zip',
        ),
    ),
    /*
    35 => array(
    "title" => "Voice Chat With PHP, jQuery, WebSocket",
    "url"      => "//subinsb.com/francium-translator",
    "d"          => "//demos.sim/php/voice-chat",
    "down"  => "//github.com/subins2000/francium-translator/archive/master.zip"
    ),*/
    37 => array(
        'id'       => 'php-google-spellcheck',
        'title'    => 'Add Spell Check In PHP Using Google',
        'url'      => '//subinsb.com/add-spell-check-using-google',
        'd'        => '//demos.sim/Francium/SpellCheck',
        'down'     => '//github.com/subins2000/francium-spellcheck/archive/master.zip',
        'download' => array(
            'service' => 'github',
            'url'     => '//github.com/subins2000/francium-spellcheck/archive/master.zip',
        ),
    ),

    39 => array(
        'id'           => 'notebook-design-text-editor',
        'title'        => 'Notebook Styled Text Editor',
        'url'          => '//subinsb.com/jquery-paper-design-text-editor',
        'd'            => '//demos.sim/css/notebook',
        'down'         => 's/ewkpe3xd7h8xzp0rzzce4o2wkcfvhmbd',
        'downloadFile' => 'notebook-styled-text-editor',
    ),

    40 => array(
        'id'       => 'advanced-chat-websocket',
        'title'    => 'Advanced Live Group Chat With PHP, jQuery & WebSocket',
        'url'      => '//subinsb.com/php-websocket-advanced-chat',
        'd'        => '//demos.sim/php/advanced-chat-websocket/',
        'down'     => '//github.com/subins2000/ws-advanced-live-group-chat/archive/master.zip',
        'download' => array(
            'service' => 'github',
            'url'     => '//github.com/subins2000/ws-advanced-live-group-chat/archive/master.zip',
        ),
    ),

    41 => array(
        'id'       => 'francium-star',
        'title'    => '5 Star Rating System With PHP',
        'url'      => '//subinsb.com/francium-star',
        'd'        => '//demos.sim/Francium/Star/',
        'down'     => '//github.com/subins2000/Francium-Star/archive/master.zip',
        'download' => array(
            'service' => 'github',
            'url'     => '//github.com/subins2000/Francium-Star/archive/master.zip',
        ),
    ),

    42 => array(
        'id'           => 'ajax-image-upload',
        'title'        => 'Upload Images Using AJAX',
        'url'          => '//subinsb.com/upload-images-html5-ajax', // //subinsb.com/uploading-images-using-ajax-in-html5
        'd'            => '//demos.sim/ajax-image-upload/',
        'down'         => '',
        'downloadFile' => '',
    ),

    43 => array(
        'id'       => 'pi',
        'title'    => 'Pi, Here I come (Finding π)',
        'url'      => '//subinsb.com/finding-the-value-of-pi',
        'd'        => '//demos.sim/pi/',
        'down'     => '//github.com/subins2000/pi/archive/master.zip',
        'download' => array(
            'service' => 'github',
            'url'     => '//github.com/subins2000/pi/archive/master.zip',
        ),
    ),

    44 => array(
        'id'           => 'seconds-to-human-readable',
        'title'        => 'Convert Seconds To Hours, Minutes, Seconds',
        'url'          => '//subinsb.com/php-convert-seconds-hours-minutes-seconds',
        'd'            => '//demos.sim/php/seconds-to-human-readable',
        'down'         => '',
        'downloadFile' => '',
    ),

    45 => array(
        'id'       => 'profile-picture-framer',
        'title'    => 'Profile Picture Framer | Support Kerala Blasters !',
        'url'      => '//subinsb.com/create-profile-picture-framer-web-app',
        'd'        => '//demos.sim/isl-profile-pic',
        'down'     => '//github.com/subins2000/profile-picture-framer/archive/master.zip',
        'download' => array(
            'service' => 'github',
            'url'     => '//github.com/subins2000/profile-picture-framer/archive/master.zip',
        ),
    ),
);
